### ISSUE TITLE
책을 출간만 하면 땡인가요

### ISSUE THREAD

**Issue by parkcolor** [bjpublic/raspberrypi#8]
프로그램 버전 업데이트에 따라 개정판을 출간하시던지.....
아님 수정되는 사항들을 깃허브나 홈페이지를 통해 알려주시기라도 하시던지.....
인간적으로 내가 책을 보고 습득하는 정보가 하나도 없습니다.
책을 통한 학습을 유도하는건지, 구글링 실력을 늘리는걸 유도하는건지...... 진짜 양심이 있으면 도서 판매도 중단해야하는거 아닌가요

**Comment by bjpublic** [comment]
안녕하세요~비제이퍼블릭입니다.
우선 책을 보는데 불편을 드려 죄송합니다.
저희도 나중에 재쇄를 찍을때 수정해야 할 부분은 수정하도록 하겠습니다.

그리고 혹시 어떤 부분이 수정해야되는지 알려주신다면 저자분과 협의하여 반영하도록하겠습니다.
또 깃허브를 통해 수정사항을 올려두겠습니다.

관심을 가지고 책을 구매하신 것에 감사드리며 다음에는 조금 더 신경을 써서 책을 제작하겠습니다.

감사합니다.

**Comment by parkcolor** [comment]
> 안녕하세요~비제이퍼블릭입니다.
> 우선 책을 보는데 불편을 드려 죄송합니다.
> 저희도 나중에 재쇄를 찍을때 수정해야 할 부분은 수정하도록 하겠습니다.
> 
> 그리고 혹시 어떤 부분이 수정해야되는지 알려주신다면 저자분과 협의하여 반영하도록하겠습니다.
> 또 깃허브를 통해 수정사항을 올려두겠습니다.
> 
> 관심을 가지고 책을 구매하신 것에 감사드리며 다음에는 조금 더 신경을 써서 책을 제작하겠습니다.
> 
> 감사합니다.

어떤부분이 수정되야하는지 제시하기엔 너무 많습니다. 진짜 너무 많습니다.
